
#-------------------------------------------------------------------------
# This file allows the DBT to know how to connect to the database. 
#-------------------------------------------------------------------------

# Set up a RDS profile
academia: #Change the profile name
  # --------------
  # Default Target
  # --------------
  # Must be one of the targets defined in the outputs
  target: dev # this is the default target
  
  outputs:
    dev:
      # Update the properties below
      type: postgres
      host: da7-data-warehouse.cre2iy7kuiri.eu-central-1.rds.amazonaws.com
      user: ctw03662
      password: 90391c652a7a9a5b96a6823544f148ad
      port: 5432
      dbname: playground
      schema: ctw03662_core
      threads: 2